import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import readline from 'node:readline/promises';

import { ADAPTER_POINTERS, REQUIRED_AGENTBUBBLE_FILES, UNKNOWN } from './constants.js';
import { detectProject } from './detect.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, '..');
const templateRoot = path.join(packageRoot, 'templates', 'base', '.agentbubble');

export async function initAgentBubble(options = {}) {
  const projectRoot = path.resolve(options.projectRoot || process.cwd());
  const destination = path.join(projectRoot, '.agentbubble');

  if (fs.existsSync(destination) && !options.force) {
    const error = new Error('.agentbubble/ already exists. AgentBubble did not overwrite it. Rerun with `agentbubble init --force` only after reviewing the existing folder.');
    error.exitCode = 1;
    throw error;
  }

  validateTemplate();
  validateRequestedAdapter(options.adapter);

  const detection = detectProject(projectRoot);
  const answers = options.nonInteractive ? {} : await askCriticalQuestions();

  if (fs.existsSync(destination) && options.force) {
    fs.rmSync(destination, { recursive: true, force: true });
  }

  copyDirectory(templateRoot, destination);

  const writtenFiles = REQUIRED_AGENTBUBBLE_FILES.map((file) => path.join('.agentbubble', file));
  writeText(path.join(destination, 'context.md'), renderContext(detection, answers));
  writeText(path.join(destination, 'architecture.md'), renderArchitecture(detection, answers));

  const adapters = writeAdapterPointers(projectRoot, detection, options.adapter);

  return {
    detection,
    filesCreated: writtenFiles,
    adapters,
    summary: renderSummary({ writtenFiles, detection, adapters })
  };
}

function validateTemplate() {
  if (!fs.existsSync(templateRoot)) {
    throw new Error(`Missing base template: ${templateRoot}`);
  }

  const missing = REQUIRED_AGENTBUBBLE_FILES.filter((file) => !fs.existsSync(path.join(templateRoot, file)));
  if (missing.length > 0) {
    throw new Error(`Base template is missing required files: ${missing.join(', ')}`);
  }
}

async function askCriticalQuestions() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  try {
    const productGoal = await rl.question('Product goal (press Enter for unknown): ');
    const doNotTouch = await rl.question('Dangerous areas agents should not touch without approval (press Enter for unknown): ');
    const qaCommand = await rl.question('QA-ready command/check (press Enter for unknown): ');
    return {
      productGoal: productGoal.trim() || undefined,
      doNotTouch: doNotTouch.trim() || undefined,
      qaCommand: qaCommand.trim() || undefined
    };
  } finally {
    rl.close();
  }
}

function copyDirectory(source, destination) {
  fs.mkdirSync(destination, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const destinationPath = path.join(destination, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, destinationPath);
    } else if (entry.isFile()) {
      fs.copyFileSync(sourcePath, destinationPath);
    }
  }
}

function writeText(filePath, content) {
  fs.writeFileSync(filePath, content, 'utf8');
}

function renderContext(detection, answers) {
  const productGoal = answers.productGoal || detection.productGoal || UNKNOWN;
  const doNotTouch = answers.doNotTouch || UNKNOWN;
  const qaCommand = answers.qaCommand || detection.testCommand || UNKNOWN;

  return `# Project Context

This file is generated by \`agentbubble init\` from deterministic local file signals. Keep it current and specific to the local codebase.

For any section that cannot be determined from the codebase, write:
${UNKNOWN}

Do not guess.
Do not infer.
Mark it and move on.

## Product Goal

${productGoal}

## Users / Audience

${UNKNOWN}

## Current Architecture

Framework: ${detection.framework}
App structure: ${detection.appStructure}
Package manager: ${detection.packageManager}

## Core Workflows

${UNKNOWN}

## Brand / Taste Rules

${UNKNOWN}

## Security Rules

${UNKNOWN}

## Database Rules

${detection.databaseTooling}

## Do Not Touch Areas

${doNotTouch}

## Known Failure Modes

${UNKNOWN}

## Definition of Good Work

QA-ready check: ${qaCommand}
`;
}

function renderArchitecture(detection, answers) {
  const qaCommand = answers.qaCommand || detection.testCommand || UNKNOWN;

  return `# Architecture

This is a lightweight architecture map generated by \`agentbubble init\` from deterministic local file signals.

For any section that cannot be determined from the codebase, write:
${UNKNOWN}

Do not guess.
Do not infer.
Mark it and move on.

## Stack

Framework: ${detection.framework}
Package manager: ${detection.packageManager}
TypeScript config: ${detection.files.tsconfig ? 'tsconfig.json' : UNKNOWN}

## App Structure

${detection.appStructure}

## Key Directories

${detection.keyDirectories}

## Important Data Models

${detection.files.prisma ? 'prisma/' : UNKNOWN}

## Auth / Permissions

${detection.authTooling}

## Payments / Billing

${UNKNOWN}

## External Services

Database/tooling: ${detection.databaseTooling}
Environment example: ${detection.files.envExample ? '.env.example' : UNKNOWN}

## Testing Commands

${qaCommand}

## Build Commands

${detection.buildCommand}

## Deployment Notes

CI tooling: ${detection.ciTooling}
`;
}

function writeAdapterPointers(projectRoot, detection, requestedAdapter) {
  if (requestedAdapter === 'none') return [];

  const adapters = new Set();

  for (const config of detection.agentConfigs) {
    if (config.includes('CLAUDE.md')) adapters.add('claude');
    if (config.includes('.cursorrules')) adapters.add('cursor');
    if (config.includes('AGENTS.md')) adapters.add('generic');
  }

  if (requestedAdapter && requestedAdapter !== 'none') {
    adapters.add(requestedAdapter);
  }

  const written = [];
  for (const adapter of adapters) {
    const pointer = ADAPTER_POINTERS[adapter];
    const filePath = path.join(projectRoot, pointer.file);
    writeManagedPointer(filePath, pointer.body);
    written.push(pointer.file);
  }

  return written;
}

function validateRequestedAdapter(requestedAdapter) {
  if (requestedAdapter && requestedAdapter !== 'none' && !ADAPTER_POINTERS[requestedAdapter]) {
    throw new Error(`Unknown adapter: ${requestedAdapter}. Use claude, cursor, codex, generic, or none.`);
  }
}

function writeManagedPointer(filePath, pointerBody) {
  const markerStart = '<!-- agentbubble:start -->';
  const markerEnd = '<!-- agentbubble:end -->';
  const block = `${markerStart}\n${pointerBody.trim()}\n${markerEnd}\n`;

  if (!fs.existsSync(filePath)) {
    writeText(filePath, `${pointerBody.trim()}\n`);
    return;
  }

  const existing = fs.readFileSync(filePath, 'utf8');
  const expression = new RegExp(`${escapeRegExp(markerStart)}[\\s\\S]*?${escapeRegExp(markerEnd)}\\n?`, 'm');
  if (expression.test(existing)) {
    writeText(filePath, existing.replace(expression, block));
  } else {
    const separator = existing.trim().length > 0 ? '\n\n' : '';
    writeText(filePath, `${existing.replace(/\s*$/, '')}${separator}${block}`);
  }
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function renderSummary({ writtenFiles, detection, adapters }) {
  const unknowns = [
    detection.productGoal === UNKNOWN ? 'product goal' : undefined,
    detection.framework === UNKNOWN ? 'framework' : undefined,
    detection.packageManager === UNKNOWN ? 'package manager' : undefined,
    detection.testCommand === UNKNOWN ? 'test command' : undefined,
    detection.buildCommand === UNKNOWN ? 'build command' : undefined,
    detection.authTooling === UNKNOWN ? 'auth tooling' : undefined,
    detection.databaseTooling === UNKNOWN ? 'database tooling' : undefined
  ].filter(Boolean);

  return `AgentBubble initialized.

Files created:
${writtenFiles.map((file) => `- ${file}`).join('\n')}

Detected stack/tooling:
- Framework: ${detection.framework}
- Package manager: ${detection.packageManager}
- Test command: ${detection.testCommand}
- Build command: ${detection.buildCommand}
- App structure: ${detection.appStructure}
- Database/auth: ${detection.databaseTooling} / ${detection.authTooling}
- CI: ${detection.ciTooling}
- Existing agent config: ${detection.agentConfigs.length > 0 ? detection.agentConfigs.join(', ') : UNKNOWN}

Unknowns remaining:
${unknowns.length > 0 ? unknowns.map((unknown) => `- ${unknown}`).join('\n') : '- none from MVP detection fields'}

Adapter pointers written:
${adapters.length > 0 ? adapters.map((adapter) => `- ${adapter}`).join('\n') : '- none'}

Next command/prompt:
- Ask your agent to read .agentbubble/session-start.md
`;
}
